services:
    bblog_cloud:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '7777:3000'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        restart: unless-stopped
        networks:
            - gumyo

networks:
    gumyo:
        external: true
